x = 10
y = 5
x+=y
print("Addition = ", x)
x-=y
print("Subtraction = ", x)
x*=y
print("Multiplication = ", x)
x/=y
print("Division = ", x)
x%=y
print("Modulus = ", x)
x**=y
print("Exponent = ", x)
x//=y
print("Floor = ", x)