print("Demonstration of escape characters in python:")

print("Newline: \n this is a new line")
print("Backslash : \\")
print("Single quote \'")
print("Double quote \"")
print("ASCII Bell \a")
print("ASCII Backspace \b!")
print("ASCII \f Formfeed")
print("ASCII Linefeed")
print("ASCII Carriage return \r here")
print("Horizontal \t tab")
print("Vertical \v tab")
print("Octal value \110\145\154\154\157\40")
print("Hex value: \x48\x65\x6c\x6c\x6f")
